# Generated by Django 4.1.3 on 2022-11-16 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GraphQLapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='exp',
        ),
    ]
